### ISSUE TITLE
error message when opening UI 

### ISSUE THREAD

**Issue by pagza** [NebulousLabs/Sia-UI#760] opened 2018-01-06 17:09 UTC
A critical error loading Sia has occured: Siad unexpectedly exited. Error log: Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
Exception 0xc0000005 0x0 0xffffffffffffffff 0xfcbc2b
PC=0xfcbc2b

syscall.Syscall(0x7ff87cf3264, 0x2, 0x184, 0x2, 0x0, 0x1e0, 0xa4a320, 0x64205b138)
	/usr/local/go/src/runtime/syscall_windows.go:163 +0x69
syscall.SetFileCompletionNotificationModes(0x184, 0x2, 0xab573e, 0x4)
	/usr/local/go/src/syscall/zsyscall_windows.go:1727 +0x6f
internal/poll.(*FD).Init(0xc04205cd20, 0xab573e, 0x4, 0xaf1e50, 0x184, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_windows.go:346 +0xf9
os.newFile(0x184, 0xc04200c6c0, 0x3d, 0xab573e, 0x4, 0x0)
	/usr/local/go/src/os/file_windows.go:57 +0x138
os.openFile(0xc04200c6c0, 0x3d, 0x441, 0x1b0, 0x0, 0xc04200c6c0, 0x0)
	/usr/local/go/src/os/file_windows.go:98 +0xff
os.OpenFile(0xc04200c6c0, 0x3d, 0x441, 0x1b0, 0xc04205b488, 0x2, 0x2)
	/usr/local/go/src/os/file_windows.go:159 +0x15e
github.com/NebulousLabs/Sia/persist.NewFileLogger(0xc04200c6c0, 0x3d, 0x2, 0xc04200c6c0, 0x3d)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:122 +0x51
github.com/NebulousLabs/Sia/modules/gateway.New(0xc04200e10b, 0x5, 0x1, 0xc04200c640, 0x31, 0x19, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:211 +0x2f0
main.(*Server).loadModules(0xc0420824b0, 0xaf1aa0, 0xc0420824b0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/server.go:465 +0x2365
main.startDaemon(0x0, 0x0, 0xc04200a30b, 0xe, 0xc04200e10b, 0x5, 0xc04200a34c, 0x5, 0x0, 0xc04200e14a, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:164 +0x1ae
main.startDaemonCmd(0xc0420b0d80, 0xc042086410, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:209 +0x169
github.com/spf13/cobra.(*Command).execute(0xc0420b0d80, 0xc042064010, 0x5, 0x7, 0xc0420b0d80, 0xc042064010)
	/home/luke/go/src/github.com/spf13/cobra/command.go:750 +0x2c8
github.com/spf13/cobra.(*Command).ExecuteC(0xc0420b0d80, 0xae2c79, 0x3b, 0xc042041a40)
	/home/luke/go/src/github.com/spf13/cobra/command.go:831 +0x315
github.com/spf13/cobra.(*Command).Execute(0xc0420b0d80, 0xefcd80, 0xacaf03)
	/home/luke/go/src/github.com/spf13/cobra/command.go:784 +0x32
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/main.go:174 +0x797

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:131 +0xad
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x29
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x48

goroutine 6 [IO wait]:
internal/poll.runtime_pollWait(0xf35060, 0x72, 0xc0420b1698)
	/usr/local/go/src/runtime/netpoll.go:173 +0x5e
internal/poll.(*pollDesc).wait(0xc0420b17d8, 0x72, 0xde1500, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xb5
internal/poll.(*ioSrv).ExecIO(0xef9158, 0xc0420b1698, 0xc042168000, 0x2, 0x1, 0x0)
	/usr/local/go/src/internal/poll/fd_windows.go:195 +0x13a
internal/poll.(*FD).acceptOne(0xc0420b1680, 0x17c, 0xc042166000, 0x2, 0x2, 0xc0420b1698, 0x370d50, 0xc04214fd08, 0x41194f, 0x10)
	/usr/local/go/src/internal/poll/fd_windows.go:748 +0xae
internal/poll.(*FD).Accept(0xc0420b1680, 0xc04215c040, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/internal/poll/fd_windows.go:782 +0x171
net.(*netFD).accept(0xc0420b1680, 0x41194f, 0x30, 0xa64440)
	/usr/local/go/src/net/fd_windows.go:192 +0x88
net.(*TCPListener).accept(0xc0420040e8, 0x58e781, 0xa64440, 0xc04215a090)
	/usr/local/go/src/net/tcpsock_posix.go:136 +0x35
net.(*TCPListener).Accept(0xc0420040e8, 0xc04200e1a8, 0x9ff480, 0xec53d0, 0xa9f1c0)
	/usr/local/go/src/net/tcpsock.go:247 +0x50
net/http.(*Server).Serve(0xc04206f040, 0xdea700, 0xc0420040e8, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2695 +0x1b9
main.(*Server).Serve(0xc0420824b0, 0xe, 0xc04200e10b)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/server.go:578 +0x4b
created by main.startDaemon
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:163 +0x19d
rax     0x0
rbx     0xefdae0
rcx     0x184
rdi     0x7fffffde000
rsi     0xc04205b070
rbp     0xc04205b020
rsp     0x23fd80
r8      0x0
r9      0x184
r10     0x3d40840
r11     0x10b4538
r12     0x0
r13     0xfa
r14     0xfa
r15     0xa
rip     0xfcbc2b
rflags  0x10246
cs      0x33
fs      0x53
gs      0x2b

**Comment by gwfc** [comment] 2018-01-13 19:14
I am getting the exact same thing on a new fresh wallet (my first Sia wallet and it will not run) on Windows 10. I have deleted all folders in %appdata% and done a LOT of recommended things in the Discord. They told me to report my issue here too:

See https://www.screencast.com/t/1QZwBb7qKGC

Please let me know.

**Comment by aaab0417** [comment] 2018-01-18 04:41
I am having the same issue on windows 10.

A critical error loading Sia has occured: Siad unexpectedly exited. Error log: Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
Exception 0xc000001d 0xffffe000fc4da080 0xffffe000fc4da080 0x18000890b
PC=0x18000890b

syscall.Syscall(0x7ffc1e37fc50, 0x2, 0x1ac, 0x2, 0x0, 0x1e0, 0xa4a320, 0x642061138)
	/usr/local/go/src/runtime/syscall_windows.go:163 +0x69
syscall.SetFileCompletionNotificationModes(0x1ac, 0x2, 0xab573e, 0x4)
	/usr/local/go/src/syscall/zsyscall_windows.go:1727 +0x6f
internal/poll.(*FD).Init(0xc042062d20, 0xab573e, 0x4, 0xaf1e50, 0x1ac, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_windows.go:346 +0xf9
os.newFile(0x1ac, 0xc04200a640, 0x3d, 0xab573e, 0x4, 0x0)
	/usr/local/go/src/os/file_windows.go:57 +0x138
os.openFile(0xc04200a640, 0x3d, 0x441, 0x1b0, 0x0, 0xc04200a640, 0x0)
	/usr/local/go/src/os/file_windows.go:98 +0xff
os.OpenFile(0xc04200a640, 0x3d, 0x441, 0x1b0, 0xc042061488, 0x2, 0x2)
	/usr/local/go/src/os/file_windows.go:159 +0x15e
github.com/NebulousLabs/Sia/persist.NewFileLogger(0xc04200a640, 0x3d, 0x2, 0xc04200a640, 0x3d)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:122 +0x51
github.com/NebulousLabs/Sia/modules/gateway.New(0xc04200e10b, 0x5, 0x1, 0xc04200a5c0, 0x31, 0x19, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:211 +0x2f0
main.(*Server).loadModules(0xc04208a4b0, 0xaf1aa0, 0xc04208a4b0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/server.go:465 +0x2365
main.startDaemon(0x0, 0x0, 0xc04200c2eb, 0xe, 0xc04200e10b, 0x5, 0xc04200c32c, 0x5, 0x0, 0xc04200e14a, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:164 +0x1ae
main.startDaemonCmd(0xc0420b6d80, 0xc04208e410, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:209 +0x169
github.com/spf13/cobra.(*Command).execute(0xc0420b6d80, 0xc042068010, 0x5, 0x7, 0xc0420b6d80, 0xc042068010)
	/home/luke/go/src/github.com/spf13/cobra/command.go:750 +0x2c8
github.com/spf13/cobra.(*Command).ExecuteC(0xc0420b6d80, 0xae2c79, 0x3b, 0xc042047a40)
	/home/luke/go/src/github.com/spf13/cobra/command.go:831 +0x315
github.com/spf13/cobra.(*Command).Execute(0xc0420b6d80, 0xefcd80, 0xacaf03)
	/home/luke/go/src/github.com/spf13/cobra/command.go:784 +0x32
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/main.go:174 +0x797

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:131 +0xad
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x29
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x48

goroutine 6 [IO wait]:
internal/poll.runtime_pollWait(0x2ef5060, 0x72, 0xc0420b7698)
	/usr/local/go/src/runtime/netpoll.go:173 +0x5e
internal/poll.(*pollDesc).wait(0xc0420b77d8, 0x72, 0xde1500, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xb5
internal/poll.(*ioSrv).ExecIO(0xef9158, 0xc0420b7698, 0xc042162000, 0x2, 0x1, 0x0)
	/usr/local/go/src/internal/poll/fd_windows.go:195 +0x13a
internal/poll.(*FD).acceptOne(0xc0420b7680, 0x1cc, 0xc042160000, 0x2, 0x2, 0xc0420b7698, 0xf606a8, 0xc04214bd08, 0x41194f, 0x10)
	/usr/local/go/src/internal/poll/fd_windows.go:748 +0xae
internal/poll.(*FD).Accept(0xc0420b7680, 0xc042158040, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/internal/poll/fd_windows.go:782 +0x171
net.(*netFD).accept(0xc0420b7680, 0x41194f, 0x30, 0xa64440)
	/usr/local/go/src/net/fd_windows.go:192 +0x88
net.(*TCPListener).accept(0xc0420040e8, 0x58e781, 0xa64440, 0xc042156090)
	/usr/local/go/src/net/tcpsock_posix.go:136 +0x35
net.(*TCPListener).Accept(0xc0420040e8, 0xc04200e1a8, 0x9ff480, 0xec53d0, 0xa9f1c0)
	/usr/local/go/src/net/tcpsock.go:247 +0x50
net/http.(*Server).Serve(0xc042071040, 0xdea700, 0xc0420040e8, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2695 +0x1b9
main.(*Server).Serve(0xc04208a4b0, 0xe, 0xc04200e10b)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/server.go:578 +0x4b
created by main.startDaemon
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:163 +0x19d
rax     0x0
rbx     0xefdae0
rcx     0x1ac
rdi     0x23fd80
rsi     0xc042061070
rbp     0xc042061020
rsp     0x23fd80
r8      0x0
r9      0x8000
r10     0x1ac
r11     0x2935e8
r12     0x0
r13     0xfa
r14     0xfa
r15     0xa
rip     0x18000890b
rflags  0x10246
cs      0x33
fs      0x53
gs      0x2b

**Comment by orbitologist** [comment] 2018-01-30 02:57
Any progress with this problem? I have the exact same problem. Tried all the normal suggestions. Still can't load UI without critical error on Loading Gateway. I am using 1.3.1. Tried it on multiple Window 10 PCs with same result.

**Comment by orbitologist** [comment] 2018-01-30 19:40
Here is my said-output.log

Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
Exception 0xc0000096 0x0 0x0 0x18000890d
PC=0x18000890d

syscall.Syscall(0x7ffb6ab6fba0, 0x2, 0x234, 0x2, 0x0, 0x1e0, 0xa4a320, 0x642061138)
	/usr/local/go/src/runtime/syscall_windows.go:163 +0x69
syscall.SetFileCompletionNotificationModes(0x234, 0x2, 0xab573e, 0x4)
	/usr/local/go/src/syscall/zsyscall_windows.go:1727 +0x6f
internal/poll.(*FD).Init(0xc042062d20, 0xab573e, 0x4, 0xaf1e50, 0x234, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_windows.go:346 +0xf9
os.newFile(0x234, 0xc04200a6c0, 0x3c, 0xab573e, 0x4, 0x0)
	/usr/local/go/src/os/file_windows.go:57 +0x138
os.openFile(0xc04200a6c0, 0x3c, 0x441, 0x1b0, 0x0, 0xc04200a6c0, 0x0)
	/usr/local/go/src/os/file_windows.go:98 +0xff
os.OpenFile(0xc04200a6c0, 0x3c, 0x441, 0x1b0, 0xc042061488, 0x2, 0x2)
	/usr/local/go/src/os/file_windows.go:159 +0x15e
github.com/NebulousLabs/Sia/persist.NewFileLogger(0xc04200a6c0, 0x3c, 0x2, 0xc04200a6c0, 0x3c)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:122 +0x51
github.com/NebulousLabs/Sia/modules/gateway.New(0xc04200e11b, 0x5, 0x1, 0xc042009e00, 0x30, 0x19, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:211 +0x2f0
main.(*Server).loadModules(0xc0420864b0, 0xaf1aa0, 0xc0420864b0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/server.go:465 +0x2365
main.startDaemon(0x0, 0x0, 0xc04200c32b, 0xe, 0xc04200e11b, 0x5, 0xc04200c36c, 0x5, 0x0, 0xc04200e15a, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:164 +0x1ae
main.startDaemonCmd(0xc0420b4d80, 0xc04208a410, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:209 +0x169
github.com/spf13/cobra.(*Command).execute(0xc0420b4d80, 0xc042068010, 0x5, 0x7, 0xc0420b4d80, 0xc042068010)
	/home/luke/go/src/github.com/spf13/cobra/command.go:750 +0x2c8
github.com/spf13/cobra.(*Command).ExecuteC(0xc0420b4d80, 0xae2c79, 0x3b, 0xc0420479a0)
	/home/luke/go/src/github.com/spf13/cobra/command.go:831 +0x315
github.com/spf13/cobra.(*Command).Execute(0xc0420b4d80, 0xefcd80, 0xacaf03)
	/home/luke/go/src/github.com/spf13/cobra/command.go:784 +0x32
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/main.go:174 +0x797

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:131 +0xad
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x29
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x48

goroutine 6 [IO wait]:
internal/poll.runtime_pollWait(0x3265060, 0x72, 0xc0420b5698)
	/usr/local/go/src/runtime/netpoll.go:173 +0x5e
internal/poll.(*pollDesc).wait(0xc0420b57d8, 0x72, 0xde1500, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xb5
internal/poll.(*ioSrv).ExecIO(0xef9158, 0xc0420b5698, 0xc042168000, 0x2, 0x1, 0x0)
	/usr/local/go/src/internal/poll/fd_windows.go:195 +0x13a
internal/poll.(*FD).acceptOne(0xc0420b5680, 0x22c, 0xc042166000, 0x2, 0x2, 0xc0420b5698, 0x3210d50, 0xc04214fd08, 0x41194f, 0x10)
	/usr/local/go/src/internal/poll/fd_windows.go:748 +0xae
internal/poll.(*FD).Accept(0xc0420b5680, 0xc04215c040, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/internal/poll/fd_windows.go:782 +0x171
net.(*netFD).accept(0xc0420b5680, 0x41194f, 0x30, 0xa64440)
	/usr/local/go/src/net/fd_windows.go:192 +0x88
net.(*TCPListener).accept(0xc0420040e8, 0x58e781, 0xa64440, 0xc04215a090)
	/usr/local/go/src/net/tcpsock_posix.go:136 +0x35
net.(*TCPListener).Accept(0xc0420040e8, 0xc04200e1b8, 0x9ff480, 0xec53d0, 0xa9f1c0)
	/usr/local/go/src/net/tcpsock.go:247 +0x50
net/http.(*Server).Serve(0xc04206f2b0, 0xdea700, 0xc0420040e8, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2695 +0x1b9
main.(*Server).Serve(0xc0420864b0, 0xe, 0xc04200e11b)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/server.go:578 +0x4b
created by main.startDaemon
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:163 +0x19d
rax     0x0
rbx     0xefdafb
rcx     0x234
rdi     0x345000
rsi     0xc042061070
rbp     0xc042061020
rsp     0x112fd80
r8      0x1
r9      0x0
r10     0x234
r11     0xd9548
r12     0x0
r13     0xfa
r14     0xfa
r15     0xa
rip     0x18000890d
rflags  0x10246
cs      0x33
fs      0x53
gs      0x2b

**Comment by orbitologist** [comment] 2018-01-31 23:44
Wanted to add a little more information that may be helpful for troubleshooting this problem. I just tried downloading and using Sia UI 1.3.0. It worked fine. The problem is something new in 1.3.1.

**Comment by lukechampine** [comment] 2018-02-01 00:50
Hmm. It seems that this is a Go-on-Windows issue. See https://github.com/moby/moby/issues/27423#issuecomment-278196016.

Are any of you running antivirus software? Can you try disabling/uninstalling it and restarting Sia?
In particular, if you are able to compile Go, can you try running this script? It will print any programs that might be causing issues: https://play.golang.org/p/5HEevQM2cL

**Comment by lukechampine** [comment] 2018-02-01 00:52
It also looks like this may be fixed in the latest Go release: https://github.com/golang/go/issues/22149

So this may be fixed in the next release of Sia simply by us compiling with Go 1.9.2 (or later).

**Comment by orbitologist** [comment] 2018-02-01 00:56
I am running Avast (antivirus) and Adaware (ad ware blocker). I have already tried disabling both. Had no effect.

**Comment by orbitologist** [comment] 2018-02-01 01:12
Ran the script:

prog.go:12:2: cannot find package "golang.org/x/sys/windows" in any of:
	/usr/local/go/src/golang.org/x/sys/windows (from $GOROOT)
	/go/src/golang.org/x/sys/windows (from $GOPATH)

Program exited.

**Comment by orbitologist** [comment] 2018-02-01 01:14
Could this be a Docker with Windows Home rather than Windows Professional/Enterprise? I am running Windows 10 Home. Is everyone else having this problem running the Home version?

**Comment by aaab0417** [comment] 2018-02-01 01:22
I am on home as well. Same result with virus protection disabled.

**Comment by gwfc** [comment] 2018-02-01 01:24
Hey folks, this is what I have https://www.screencast.com/t/VhR7LFrAiwdx FYI Sia 1.3.0 still did not work for me. Same issue. I ONLY have Windows stock antivirus and firewall for windows. I have tried disabling both even and doing fresh installs and deleting the Sia %appdata% folder to multiple times FYI.

**Comment by gwfc** [comment] 2018-02-01 04:17
Guys/Gals: I found out what the issue is I believe. I tried on another computer. It was Windows 10 PRO FYI.

When I did a fresh install of 1.3.1 and ran the executable file, it THEN prompted me for THIS https://www.screencast.com/t/z8La7c1Bz7Z I allowed it (it is working on the 2nd computer that prompted for this and I had the opportunity to allow it)! HOWEVER, on the laptop that does not run Sia it NEVER has ever prompted me for that so I can not allow it (happens to be Windows Home version if that matters). In any case, this is likely the issue! So, #1 in Window Home (or any version of Windows). How do we reset the Windows Defender so it allows this prompt again? Then, once we allow it will very likely work.

Let me know your thoughts?

:)

Greg

**Comment by orbitologist** [comment] 2018-02-01 04:28
I still think it is a Windows Pro versus Home issue and not the defender firewall. You can manually go into the control panel/windows defender firewall/add apps and add a check for siad.exe private & public. I did this on day one and it did not help. You did demonstrate Pro working and Home not.

**Comment by gwfc** [comment] 2018-02-01 04:32
Yea. Windows 10 Pro is working because (I believe) it gave me the opportunity to "Allow" the permissions. But I NEVER was presented with the opportunity to "Allow" permissions with Windows 10 Home which is my point. Perhaps in Sia's code they can make sure Windows 10 Home prompts for this permission? Is that what you are thinking? Just some additional info if not anything else . . . smile.

**Comment by orbitologist** [comment] 2018-02-01 04:45
Nope. I don't think you are understanding. Home and Pro should both prompt you to allow siad.exe through the firewall. My Home version did, I allowed, and it still does not work. You can also manually allow access through the firewall the way I described above. The firewall has no relationship to this problem. You can prove this to yourself by allowing firewall permission on your Home machine. Still won't work.

**Comment by gwfc** [comment] 2018-02-01 04:56
Ok. Fine. I see. But, I am saying, for me, it never prompted me at all FYI. So, it must be something else and/or related in some way. But, there may be some background code that triggers on the Sia software perhaps  when that prompt is "allowed" or accepted. I hear you on manually allowing from the Windows side. Ok. Either way, I guess there is still SOME (related or not to what I found in my experience) issue with Windows 10 Home and perhaps Pro development team. So, please let us know?

It is working on my Windows 10 PRO version but have no idea why it is vs. my other machine (Windows 10 Home) . . . 

Night.

**Comment by lukechampine** [comment] 2018-02-01 20:30
@orbitologist you need to run `go get golang.org/x/sys/windows` first.

I've compiled a version of `siad.exe` using Go 1.9.3, which you can find [here](https://pixeldra.in/u/bAuZr6). Please give it a try. To install it, first shutdown Sia-UI. Then, in the folder that contains Sia-UI.exe, navigate to the `resources/app/Sia` folder. There should be a `siad.exe` inside. Replace it with the new `siad.exe`, and then launch Sia-UI.

**Comment by orbitologist** [comment] 2018-02-01 21:26
@lukechampine Thank you. Just went to try it. That file set off all my virus protection. I would have to shut off my virus protection (Avast) to download. Never had that happen before. Know what's triggering that?

**Comment by orbitologist** [comment] 2018-02-01 21:47
@lukechampine I had to make exceptions for this file in Avast and Windows Defender. That feels a little like unprotected sex with a stranger. However, IT WORKED!!! I am running Sia UI 1.3.1 on Windows 10 Home for the first time. Luke, you are a gentleman and scholar!

**Comment by gwfc** [comment] 2018-02-01 21:54
@lukechampine  Will that fix be baked into the next release of the wallet?

**Comment by ChrisSchinnerl** [comment] 2018-02-01 21:59
@gwfc It will probably be fixed since it doesn't seem to be directly related to Sia but to the version of Go used to build Sia. This means we can just use the most recent version of Go for the next release.

**Closed as completed by ChrisSchinnerl** 2018-02-01 21:59 UTC

**Comment by gwfc** [comment] 2018-02-01 22:01
@ChrisSchinnerl  Fantastic! Thanks Chris. Looking forward to that . . . smile. Ok.
