### ISSUE TITLE
ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by bent-rasmussen** [NebulousLabs/Sia-UI#657] opened 2017-07-05 19:17 UTC
Getting a heck of a lot of these errors in Sia-UI (tens of identical dialog popups in a row). CTRL+C => CTRL+V from dialog:

[Window Title]
Error

[Main Instruction]
Sia-UI Files Error

[Content]
ESOCKETTIMEDOUT

[OK]

Not sure what it means or if its somehow specific to my machine or scenarios.

Should I be worried about some files not uploading?

Sia & Sia-UI version = 1.2.2
Update: Windows 10 (Insider Preview)

**Comment by pavelpp** [comment] 2017-07-28 07:35
I have the same issue on Mac OS with 1.3.0

**Comment by hklkf200553** [comment] 2017-07-28 11:03
have the same issue

**Comment by contenidosonline** [comment] 2017-08-01 11:53
same with ubuntu and  Sia UI version: v1.3.0
Sia version: 1.3.0

**Comment by Twitchykid** [comment] 2017-09-06 01:16
I am having this same issues on ubuntu 14.04 Sia UI version v1.3.0

However, I only started seeing when I tried uploading more than 2 files at once. The size of the 2 files are about 2 and 1 GB each.

**Comment by tbenz9** [comment] 2017-12-06 18:58
Duplicate of https://github.com/NebulousLabs/Sia/issues/1605
This is one of the most common bugs in Sia, the devs are well aware of it.

Recommendation to devs: Close as duplicate

**Closed as completed** 2017-12-06 19:37 UTC
