### ISSUE TITLE
i got this error :/

### ISSUE THREAD

**Issue by NicolasMuzette** [NebulousLabs/Sia-UI#737] opened 2017-12-04 22:37 UTC
```
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 8.293256 seconds
panic: assertion failed: read: zero-length inode key

goroutine 14 [running]:
github.com/NebulousLabs/bolt._assert(0xa76800, 0xaed7cf, 0x1b, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:1034 +0xfd
github.com/NebulousLabs/bolt.(*node).read(0xc062533f10, 0x1073b000)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:178 +0x1e2
github.com/NebulousLabs/bolt.(*Bucket).node(0xc059bd2040, 0xd48b, 0xc062533030, 0xc062533030)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:666 +0x15f
github.com/NebulousLabs/bolt.(*node).childAt(0xc062533030, 0xe, 0x14)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:77 +0x66
github.com/NebulousLabs/bolt.(*Cursor).node(0xc068773270, 0xc05d6048c0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:373 +0x152
github.com/NebulousLabs/bolt.(*Bucket).Put(0xc059bd2040, 0xc05d6048c0, 0x20, 0x20, 0xf06bb0, 0x0, 0x0, 0xc058a38180, 0xde2420)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:309 +0x233
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).putTransaction(0xc04200f1e0, 0xc06d586e00, 0xae9214b0c9420a51, 0xfb98855d668bc9d7, 0x4a95e23c646dff91, 0xf70a93c5a24ebbf3, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/database.go:123 +0xf3
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).ProcessConsensusChange(0xc04200f1e0, 0x81e0d4140d8a87c6, 0x9baf757a34e2f94d, 0xf30bb77f6e85b664, 0xccca44552cf6b020, 0x0, 0x0, 0x0, 0xc05a1467e0, 0x1, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/update.go:200 +0x49e
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).updateSubscribers(0xc042113b80, 0x0, 0x0, 0x0, 0xc07f256a80, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:114 +0x17a
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks(0xc042113b80, 0xc064d48000, 0xa, 0xa, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:338 +0x750
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc042113b80, 0xde41c0, 0xc05f32e880, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:225 +0x5be
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.managedReceiveBlocks)-fm(0xde41c0, 0xc05f32e880, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:445 +0x45
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc04200edc0, 0xc04218ef20, 0x14, 0xaddb78, 0xa, 0xc05f329a00, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:66 +0x339
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc04200edc0, 0xc04218ef20, 0x14, 0xaddb78, 0xa, 0xc05f329a00, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:76 +0xd8
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc042113b80, 0xc068775ef0, 0xc068775eb0, 0xc068775eb8, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:580 +0x133
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc042113b80, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:601 +0x30e
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc04223aa60, 0xc042113b80, 0xde4440, 0xc04200edc0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:151 +0x404
created by github.com/NebulousLabs/Sia/modules/consensus.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:182 +0x641
https://github.com/NebulousLabs/Sia-UI/issues/new
```

**Comment by tbenz9** [comment] 2017-12-05 03:14
This is likely an issue in the Bolt package.  Related (but different) to https://github.com/NebulousLabs/Sia/issues/2247

As far as I know there is not a solution yet.

**Comment by tbenz9** [comment] 2017-12-19 00:28
Duplicate of https://github.com/NebulousLabs/Sia/issues/2551

**Closed as completed** 2017-12-19 00:59 UTC
