### ISSUE TITLE
Add window icon

### ISSUE THREAD

**Issue by Fornax96** [NebulousLabs/Sia-UI#371] opened 2016-07-20 09:57 UTC
Currently the window is shown as a big question mark on my application dock: 
![image](https://cloud.githubusercontent.com/assets/1247928/16982044/0c59a744-4e6e-11e6-91b6-e7f8081605bf.png) 

This can be confusing since it's not easily distinguished from other apps that don't have a window icon. 

I thought I would be able to fix this myself and started messing around with this line: https://github.com/NebulousLabs/Sia-UI/blob/master/js/mainjs/initWindow.js#L17, but I couldn't get it to work, it always shows the question mark. This makes me think the problem lies a bit deeper than just the icon path.

**Comment by DavidVorick** [comment] 2016-07-20 12:37
I believe that you need to use a specific Windows-only program to get icons added to Windows binaries. It was a part of our release process at one point, but may have gotten left out at some point as we iterated on our build design. Shouldn't be too hard to fix.

**Comment by droghio** [comment] 2016-07-20 15:53
@Fornax96 Thanks for the issue report. Just to double check which OS are you running. Your picture looks like a GNOME dock to me.

**Comment by Fornax96** [comment] 2016-07-20 17:05
It's Ubuntu 16.04 Unity desktop

**Comment by DavidVorick** [comment] 2016-07-20 17:39
:< hmm ok

I should have known that

**Comment by droghio** [comment] 2016-07-20 17:58
Looks like this error has been patched an a recent version of Electron: https://github.com/electron/electron/pull/6323
I will double check that was the problem before closing the issue.

**Comment by droghio** [comment] 2016-07-21 00:26
So the missing icon is caused by two bugs:
1. Due to https://github.com/electron/electron/issues/6205 for Ubuntu/Linux support the icon must be called `icon.png` and be 128x128px if we want to keep using electron 1.2.2. I believe there were bugs in the electron 1.2.3 build which is why we held back.
2. Once we build the js into a release the relative pathing changes since we use web-pack. The icon path needed to be updated.

I have a pull request ready for the path update and a few other minor UI changes but the question is whether we should make the default icon size 128x128px or leave it as 64x64px. I'm not sure if that size is necessary to build the Mac icon. We also need to decide whether to update the electron dependency to `>1.2.2` or leave it as is for now.

@johnathanhowell Any thoughts?

**Comment by droghio** [comment] 2016-07-21 19:49
Fixed in PR #374

**Closed as completed by droghio** 2016-07-21 19:49 UTC
